version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
  backend:
    build: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app